### ISSUE TITLE
Test effort

### ISSUE THREAD

**Issue by animeshsingh** [IBM/Microservices-with-Istio-Service-Mesh-on-Kubernetes#8]
@Tomcli and @szihai please give it a run, as well look for dead links etc.

**Comment by Tomcli** [comment]
@AnthonyAmanse The toolchain instructions you are pointing to is the old one(that's the one we need to do the re-deploy), the new toolchian instructions is located here - https://github.com/IBM/container-journey-template/blob/master/Toolchain_Instructions_new.md

**Comment by szihai** [comment]
works for me. I followed the steps and the everything goes through.
